### ISSUE TITLE
[BUG]:  FileSystemResource ACL Attributes "owner" and "group" have "name" and "type" set to Required, should be Optional

### ISSUE THREAD

**Issue by petew-nfx** [dell/terraform-provider-powerscale#118]
### Bug Description

Optional attributes on ACLs are marked as Required - import FilesystemResource fails on nil pointer.
Namespace objects with unresolvable UID/GID on the cluster lack a "name" and a "type" attribute for the ACL.

### Resource or DataSource Name

FileSystem

### Terraform Version

Terraform 1.6.6

### go Version

go 1.21.5

### Unisphere Version

N/A

### Operating System

MacOS Darwin Kernel Version 23.2.0

### Terraform File Used

```
resource "powerscale_filesystem" "some_path" {
}
```
### Logs

```
% terraform import powerscale_filesystem.some_path ifs/<some_path>

 ╷
 │ Error: Plugin did not respond
 │
 │ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ImportResourceState call. The plugin
 │ logs may contain more details.
 
 Stack trace from the terraform-provider-powerscale_v1.1.0 plugin:
 
 panic: runtime error: invalid memory address or nil pointer dereference
 [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x242dbe9]
 
 goroutine 37 [running]:
 terraform-provider-powerscale/powerscale/helper.UpdateFileSystemResourceState({0x2f69cf0?, 0xc0003df1d0?}, 0x2d961c0?, 0xc00008b040, 0xc0000bc2c0, 0x0?)
 	terraform-provider-powerscale/powerscale/helper/file_system_helper.go:297 +0x189
 terraform-provider-powerscale/powerscale/provider.(*FileSystemResource).ImportState(0xc000416130, {0x2f69cf0, 0xc0003df1d0}, {{0xc0001a0228?, 0x2db58df?}}, 0xc000180960)
 	terraform-provider-powerscale/powerscale/provider/file_system_resource.go:516 +0x109
 github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ImportResourceState(0xc0002191e0, {0x2f69cf0, 0xc0003df1d0}, 0xc0001a6ba0, 0xc0002495c8)
...
```
A GET of namespace/ifs/<some_path> via the REST API returns:
```
{
  "acl": [
    {
      "accessrights": [
        "dir_gen_all"
      ],
      "accesstype": "allow",
      "inherit_flags": [],
      "trustee": {
        "id": "UID:99"
      }
    },
    {
      "accessrights": [
        "dir_gen_all"
      ],
      "accesstype": "allow",
      "inherit_flags": [],
      "trustee": {
        "id": "GID:99"
      }
    },
    {
      "accessrights": [
        "dir_gen_all"
      ],
      "accesstype": "allow",
      "inherit_flags": [],
      "trustee": {
        "id": "SID:S-1-1-0",
        "name": "Everyone",
        "type": "wellknown"
      }
    }
  ],
  "authoritative": "acl",
  "group": {
    "id": "GID:99"
  },
  "mode": "0777",
  "owner": {
    "id": "UID:99"
  }
}
```

### Steps to Reproduce

> terraform import powerscale_filesystem.some_path ifs/<some_path>

Where some_path has uid/gid set which do not resolve on the cluster providers.

### Expected Behavior

Importing a Filesystem with an unresolvable UID/GID in the ACL should succeed.

### Actual Behavior

Importing a Filesystem with an unresolvable UID/GID in the ACL fails with a panic.

**Comment by taohe1012** [comment]
hi @petew-nfx may I know your onefs version.

**Comment by petew-nfx** [comment]
Hey @taohe1012 , sorry, I should have supplied that.
9.4.0.13

**Comment by taohe1012** [comment]
thanks @petew-nfx , 
normally, in response, its "group" or "owner" should have id, name and type params, but in your API response , it only has id param. 
The error is due to the "group" or "owner" 's name and type params are not existed, not by the optional or required type.
and checked your response, found that difference between   
    "trustee": {
        "id": "GID:99"
      }
and  ```
"trustee": {
        "id": "SID:S-1-1-0",
        "name": "Everyone",
        "type": "wellknown"
      }
```
could help check the resource's owner or group is existed or valid?

**Comment by petew-nfx** [comment]
I agree, that is the difference between the responses. However, the response I get is valid, but the import fails due to the Required setting.
The UID and GID are not expected to be resolvable on the cluster as the filesystem metadata is managed client-side by services the cluster does not and should not have access to.

**Comment by taohe1012** [comment]
@petew-nfx yes, thinking we need to allow the params to be empty. 
what's your thought? @doriac11 @nikitajoshi1

**Comment by forrestxia** [comment]
@petew-nfx Can you replicate/recreate this issue to dell terraform providers repo https://github.com/dell/dell-terraform-providers/issues ? We use that repo to track community issues. Anyway, thanks for reporting this issue.

**Comment by forrestxia** [comment]
Once you replicate it there, we will remove issue tracking function in this repo.

**Comment by petew-nfx** [comment]
Created https://github.com/dell/dell-terraform-providers/issues/9

**Comment by forrestxia** [comment]
Close this issue and disable issue function in this repo. Will use https://github.com/dell/dell-terraform-providers/issues to report dell terraform providers issues centrally.
